### ISSUE TITLE
Add icons for various weather conditions

### ISSUE THREAD

**Issue by ghost** [PugliaSOS/howsweather#3]

**Comment by mariolamacchia** [comment]
@domcorvasce need help for this one?

**Comment by ghost** [comment]
Do you know a good package which already implements weather icons?
I don't want to hardcode ASCII icons on howsweather.

**Comment by mariolamacchia** [comment]
It isn't bad to store ASCII images: it's the same thing you would do with png images.
Anyway I was more thinking about unicode emoji ( 👍  💯  🔢  ... ).

Maybe we can take this conversation as an opportunity and think about a way to let the user create a template

**Comment by ghost** [comment]
What a template?
Do you intend let user decide about how show results?

**Comment by mariolamacchia** [comment]
Yes, we provide a default template but the user can change it without changing the code
